on:
  workflow_dispatch:
  push:
    branches:
      - "master"

# https://github.com/OWNER/REPO/settings/actions
# MUST CHANGE GITHUB_TOKEN PERMISSION FROM READ TO WRITE
# MUST CHANGE GITHUB_TOKEN PERMISSION ALLOW PULL REQUESTS
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Release please create a pull request to the 'main' branch
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: maven
          #package-name: release-please-action
